# Generated by Django 5.2.6 on 2025-09-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='My_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('info', models.TextField()),
                ('price', models.CharField(max_length=100000000)),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('code', models.CharField(max_length=4)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
