# Generated by Django 5.2.6 on 2025-09-14 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='iteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='item', max_length=200)),
                ('price', models.CharField(default='0', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='sabad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(default='0', max_length=100)),
                ('sabad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Iteam_sabad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('ite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sabad.iteam')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iteam_token', to='sabad.sabad')),
            ],
        ),
        migrations.AddField(
            model_name='iteam',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sabad.sabad'),
        ),
    ]
